# Generated by Django 6.1 on 2026-08-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('Técnico', 'Técnico'), ('Graduação', 'Graduação'), ('Pós-graduação', 'Pós-graduação')], default='Sistemas', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='nome_mae',
            field=models.CharField(default='maria', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='periodo',
            field=models.CharField(default='5', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(default='960604345', max_length=20),
            preserve_default=False,
        ),
    ]
